### ISSUE TITLE
send method ignores timetamp field 

### ISSUE THREAD

**Issue by alfamegaxq** [narcisoguillen/kafka-node-avro#15]
As in documentation of the send method parameters: 

> timestamp : Date.now() // <-- defaults to Date.now() (only available with kafka v0.10 and KafkaClient only)

kafka-node producer could take advantage of this timestamp parameter as we can see in kafka-node/lib/baseProducer.js `return new Message(0, 0, p.key, message, p.timestamp || Date.now());`

But when I pass timestamp to kafka-node-avro it is ignored and default `Date.now()` is used
```
             client.send({
                        topic: 'my-topic',
                        key: 123,
                        timestamp: 1578400460000, // this parameter ignored
                        messages: {
                            data: 'my-data',
                            timestamp: 1578400460000,
                            action: 'my-data'
                        }}); 
```

This field shouldn't be ignored.

**Comment by alfamegaxq** [comment]
I have created a pull request for this issue. Please take a look: https://github.com/narcisoguillen/kafka-node-avro/pull/16

**Comment by narcisoguillen** [comment]
Hey thanks for helping making kafka-node-avro better

**Comment by narcisoguillen** [comment]
I just add a change so it applies to any other field being sent , such us `partition` or `attributes`
