### ISSUE TITLE
Support Secure Registry

### ISSUE THREAD

**Issue by ReeganExE** [narcisoguillen/kafka-node-avro#21]
Hi,

My registry is served on HTTPS endpoint. Does `kafka-node-avro` support to pass a CA cert as a constructor parameter?

Thanks,

**Comment by narcisoguillen** [comment]
Hey @ReeganExE sorry for taking so long to answer, had a lot of work and is hard to free my self up. This seems to me more like a `kafka-node` question. Based on the configuration [Options](https://github.com/SOHU-Co/kafka-node#options) . And an answer from one of their issues [here](https://github.com/SOHU-Co/kafka-node/issues/1185#issuecomment-521158472)
you can set this ip on the settings like 

```
const Settings  = {
  "kafka" : {
    "kafkaHost"  : "localhost:9092",
    "sslOptions" : {
      "rejectUnauthorized" : ...
      "ca"                 : ...
      "cert"               : ...
      "key"                : ...
      "passphrase"         : ...
    }
  },
  "schema": {
    "registry" : "http://localhost:8081"
  }
};

```

**Comment by ReeganExE** [comment]
> Hey @ReeganExE sorry for taking so long to answer, had a lot of work and is hard to free my self up. This seems to me more like a `kafka-node` question. Based on the configuration [Options](https://github.com/SOHU-Co/kafka-node#options) . And an answer from one of their issues [here](https://github.com/SOHU-Co/kafka-node/issues/1185#issuecomment-521158472)
> you can set this ip on the settings like
> 
> ```
> const Settings  = {
>   "kafka" : {
>     "kafkaHost"  : "localhost:9092",
>     "sslOptions" : {
>       "rejectUnauthorized" : ...
>       "ca"                 : ...
>       "cert"               : ...
>       "key"                : ...
>       "passphrase"         : ...
>     }
>   },
>   "schema": {
>     "registry" : "http://localhost:8081"
>   }
> };
> ```

I meant the schema `registry`, not kafka.

**Comment by narcisoguillen** [comment]
Oh right, sorry my bad. no it does not, but lets make it happen ! ... we could add a way to provide any [Option](https://github.com/request/request#requestoptions-callback) to the Registry class, what about something like 

```
const Settings  = {
  "kafka" : {
    "kafkaHost" : "localhost:9092"
  },
  "schema": {
    "registry" : "http://schemaregistry.example.com:8081",
    "options: : {
         cert: fs.readFileSync(certFile),
         key: fs.readFileSync(keyFile),
         passphrase: 'password',
         ca: fs.readFileSync(caFile)
    }
  }
};
```

so we can set up the [TLS/SSL options](https://github.com/request/request#tlsssl-protocol). What do you think ?

**Comment by narcisoguillen** [comment]
Just added on Settings schema options, you should be able to config any option on the schema now. like 

```
const Settings  = {
  "kafka" : {
    "kafkaHost" : "localhost:9092"
  },
  "schema": {
    "registry" : "http://schemaregistry.example.com:8081",
    "options: : {
         cert: fs.readFileSync(certFile),
         key: fs.readFileSync(keyFile),
         passphrase: 'password',
         ca: fs.readFileSync(caFile)
    }
  }
};
```
