### ISSUE TITLE
Bundle typings for typescript

### ISSUE THREAD

**Issue by boissierflorian** [narcisoguillen/kafka-node-avro#23]
Hello, 

It would be a great feature if typing declarations are bundled within the project.

**Comment by narcisoguillen** [comment]
Thanks for using **kafka-node-avro**, at the beginning this library was 100% ECMA5 and today I am slowly migrating it to ES2019, the idea around this is to make it work across any environment, reason why kafak-node is a peer dependency. If we make it typescript then we loose this goal, thanks a lot for the feedback and for trying to make this package better ( cheers ! )
