### ISSUE TITLE
kafka-node should be a peerDependency

### ISSUE THREAD

**Issue by crobinson42** [narcisoguillen/kafka-node-avro#3]

**Comment by narcisoguillen** [comment]
Hey thanks a lot for using kafka-node-avro, why is that ? wouldn't that cause an issue if an older or newer version of `kafka-node` is install as peer and does not work with the version that kafka-node-avro is test it with ?

**Comment by crobinson42** [comment]
Well if you stick with with your major versioning in parallel with kafka-node, it technically shouldn't break anything.

**Comment by crobinson42** [comment]
The problem with it being a dependency in this project is the manual requirement for always staying up to date with publishing a new release when kafka-node changes - what if you get hit by a bus today and kafka-node publishes a new release tomorrow... just saying :-)

**Comment by narcisoguillen** [comment]
Oh good point, I like the way you think. I'll migrate kafka-node dependency to a peer dependency and release as 1.0.2

**Comment by crobinson42** [comment]
Well that’s a breaking change - also the latest version of Kafka-node is 4.1.3

So this project should release 4.0.0 with Kafka-node as a peerDep - and I would make it a statement on the README so everyone is aware.

And finally, probably make a graceful/descriptive error that throws on start-up if `require('kafka-node’)` fails to load, ie: it’s not installed

**Comment by narcisoguillen** [comment]
Would you like to help me out making this package better with a contribution ? that would be awesome.

**Comment by crobinson42** [comment]
Yeah! I’ll try and put a PR together when I have some time next week.

**Comment by narcisoguillen** [comment]
Hey thanks, here a PR I made, let me know what you think : https://github.com/narcisoguillen/kafka-node-avro/pull/4
