### ISSUE TITLE
How can I close producer

### ISSUE THREAD

**Issue by wips** [narcisoguillen/kafka-node-avro#6]
After I run my script I can't close producer and the script never finishes. Is it possible to do it somehow in current version?

**Comment by narcisoguillen** [comment]
Hey ! , thanks for using kafka-node-avro, oh ! you are right it has no close mechanism, I will start to write that on a branch and add a test to it, you are welcome to help if you want.

I'm planning on adding a general `close` mechanism as 

```
 kafka.close( closed => {
   // - close all open consumers 
   // - close all open producers 
   // - flush schema pool ( clean ) 
   // - close kafka client
 });
```

Tanks for helping making this lib better.

**Comment by narcisoguillen** [comment]
I started the PR for this new feature : https://github.com/narcisoguillen/kafka-node-avro/pull/7

**Comment by FrancoisXavierNoe** [comment]
Hello,
Do you have any idea of when this feature can be availlable ?
Thanks,
