### ISSUE TITLE
Producer configuration options

### ISSUE THREAD

**Issue by cadeparker-civitas** [narcisoguillen/kafka-node-avro#8]
I'm trying to find a way to configure the `acks` Kafka Producer config property, but I don't see an obvious way to override the producer client used by kafka-node-avro. The `kafka-node` project uses custom options to do this (the `acks` config is mapped from the `requireAcks` producer option), and it looks like `kafka-node-avro` just uses the default values. How can I configure this value easily in my project when I initialize `KafkaAvro`?

**Comment by narcisoguillen** [comment]
Hey thanks for using kafka-node-avro , sorry for the delay had a lot of work ... You are right so far this library uses default settings, I will write an `addProducer` and with that the ability to send ` [options], [customPartitioner]` on the * HighLevelProducer*

**Comment by narcisoguillen** [comment]
I just add this new mechanism : https://github.com/narcisoguillen/kafka-node-avro#addproduceroptions-custompartitioner
