### ISSUE TITLE
Schema Registry with Basic Authentication

### ISSUE THREAD

**Issue by brunodomenici** [narcisoguillen/kafka-node-avro#9]
Hello,

Nice job with this project!

Our Schema Registry use Basic Authentication, can we include parameters for Basic Auth in [request http-authentication](https://github.com/request/request#http-authentication)?

https://github.com/narcisoguillen/kafka-node-avro/blob/ff25715ae576a3a8119da0cdaa77d36c1a12f973/lib/registry.js#L6-L13

I can contribute if you want.

Thank you.

**Comment by brunodomenici** [comment]
Well, I just saw that we can set it in http://username:password@url. My problem it was that I wasn't encoding my password.
Thanks!

**Comment by narcisoguillen** [comment]
Hey thanks for using kafka-node-avro !!  ... If you want to contribute you are welcome to 🍺  , the idea is to make this library better.
